name: Tests EasyCrypto using CI process
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Xcode
        run: sudo Xcode-select -switch /Applications/Xcode_15.0.app
      - name: Build & Test
        run: xcodebuild test -scheme EasyCrypto -project EasyCrypto.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 14' | xcpretty -s
